# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: kaectl

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - <<: &build_defaults
      binary: bin/kaectl
      main: ./cmd/kaectl
      ldflags:
        - -s -w -X github.com/kaecloud/kaectl/version.Version={{.Version}} -X github.com/kaecloud/kaectl/version.BuildDate={{time "2006-01-02"}}
    id: macos
    goos: [darwin]
    goarch: [amd64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, amd64, arm64]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]

archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    replacements:
      darwin: macOS
    format: tar.gz
    files:
      - LICENSE
      - ./share/man/man1/gh*.1
  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
